import:
    - "%root_dir%/app/parameters.yml"

debug: %debug%
mode: "%mode%"

# Paths
app_dir:        "%root_dir%/app"
data_dir:       "%root_dir%/data"
cache_dir:      "%data_dir%/cache"
migration_dir:  "%app_dir%/migrations"
seed_dir:       "%app_dir%/seeds"

# Routes
routes:
  - "LocalBooking\\Controller\\CatalogController"


api:
  prefix: "/api"
  version: 1
  headers:
    Content-Type: "application/json; charset=utf-8"
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Methods: "GET,POST,PUT,DELETE"
  resources:
    resource:
      model: "LocalBooking\\Model\\Resource"
